import { ReactNode } from 'react';

export interface ChatMessage {
  id: number;
  sender: 'bot' | 'user';
  content: ReactNode;
  timestamp: string;
}

export enum WorkflowState {
  // Initial State
  WELCOME,

  // New Client States
  NEW_CLIENT_MENU,
  NEW_CLIENT_QUOTATION,
  NEW_CLIENT_QUOTATION_COMPANY,
  NEW_CLIENT_QUOTATION_CONTACT,
  NEW_CLIENT_QUOTATION_EMAIL,
  NEW_CLIENT_QUOTATION_PRODUCT,
  NEW_CLIENT_QUOTATION_QUANTITY,
  NEW_CLIENT_QUOTATION_CONFIRM,
  NEW_CLIENT_MEETING,
  NEW_CLIENT_MEETING_TIME,
  NEW_CLIENT_LEARN,
  NEW_CLIENT_GENERAL,

  // Existing Client States
  EXISTING_CLIENT_MENU,
  EXISTING_CLIENT_TRACK_ORDER,
  EXISTING_CLIENT_TRACK_ORDER_ID,
  EXISTING_CLIENT_CHECK_INVOICE,
  EXISTING_CLIENT_CHECK_INVOICE_ID,
  EXISTING_CLIENT_TECH_SUPPORT,
  EXISTING_CLIENT_TECH_SUPPORT_DETAILS,
  EXISTING_CLIENT_COMPLAINT,
  EXISTING_CLIENT_COMPLAINT_DETAILS,

  // Vendor States
  VENDOR_MENU,
  VENDOR_REGISTER_DELIVERY,
  VENDOR_REGISTER_DELIVERY_PO,
  VENDOR_REGISTER_DELIVERY_SUPPLIER,
  VENDOR_REGISTER_DELIVERY_ITEMS,
  VENDOR_REGISTER_DELIVERY_QUANTITY,
  VENDOR_REGISTER_DELIVERY_VEHICLE,
  VENDOR_REGISTER_DELIVERY_SUMMARY,
  VENDOR_REGISTER_DELIVERY_CONFIRM,
  VENDOR_BOOK_SLOT,
  VENDOR_GET_INSTRUCTIONS,
  VENDOR_CONFIRM_ARRIVAL,
  VENDOR_CONFIRM_UNLOADING,

  // Internal Staff States
  INTERNAL_STAFF_MENU,
  INTERNAL_STAFF_CONFIRM_DELIVERY,
  INTERNAL_STAFF_CONFIRM_DELIVERY_ID,
  INTERNAL_STAFF_REPORT_ISSUE,
  INTERNAL_STAFF_REPORT_ISSUE_TYPE,
  INTERNAL_STAFF_REQUEST_SUPPORT,

  // Closing
  FEEDBACK,
  END
}

export interface Option {
  text: string;
  nextState: WorkflowState;
  payload?: any;
}

export interface FormData {
  [key: string]: string;
}
